In [1]:
print("hello world")

hello world


In [3]:
# Shift + enter
print("hello")

hello


In [4]:
! pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.


In [5]:
import numpy as np

In [14]:
arr = np.array([1,4,7,9])

In [15]:
arr.shape

(4,)

In [31]:
arr1 = np.random.randint(10,100, size=(3,3))

In [32]:
arr1.shape

(3, 3)

In [33]:
arr1

array([[51, 88, 76],
       [22, 44, 89],
       [85, 46, 73]])

In [34]:
arr2 = np.random.randint(10,100, size=(1,3))

In [36]:
arr2

array([[84, 70, 71]])

In [37]:
arr1 + arr2

array([[135, 158, 147],
       [106, 114, 160],
       [169, 116, 144]])

In [38]:
2+arr1

array([[51, 88, 76],
       [22, 44, 89],
       [85, 46, 73]])

In [39]:
arr1

array([[51, 88, 76],
       [22, 44, 89],
       [85, 46, 73]])

In [40]:
arr3 = np.random.randint(10,100, size=(5,5))

In [41]:
arr3

array([[97, 91, 64, 34, 33],
       [95, 54, 59, 97, 52],
       [27, 36, 60, 34, 45],
       [15, 82, 28, 69, 47],
       [10, 37, 73, 76, 54]])

In [ ]:
# Array Slicing
arr[  start_row : end_row+1 , start_col : end_col +1    ]

In [45]:
arr3[2: 4 , 2 :5]

array([[60, 34, 45],
       [28, 69, 47]])

In [46]:
def distance(pA, pB):
    return np.sqrt(np.sum((pB-pA)**2))

In [49]:
pA = np.array([5,6,9,2,7])
pB = np.array([2,6,0,2,1])

In [50]:
distance(pA, pB)

11.224972160321824

In [53]:
np.transpose(arr3)

array([[97, 95, 27, 15, 10],
       [91, 54, 36, 82, 37],
       [64, 59, 60, 28, 73],
       [34, 97, 34, 69, 76],
       [33, 52, 45, 47, 54]])

In [54]:
arr3.T

array([[97, 95, 27, 15, 10],
       [91, 54, 36, 82, 37],
       [64, 59, 60, 28, 73],
       [34, 97, 34, 69, 76],
       [33, 52, 45, 47, 54]])

In [56]:
arr1

array([[51, 88, 76],
       [22, 44, 89],
       [85, 46, 73]])

In [57]:
arr2

array([[84, 70, 71]])

In [58]:
arr2*arr1

array([[4284, 6160, 5396],
       [1848, 3080, 6319],
       [7140, 3220, 5183]])

In [59]:
np.dot(arr2, arr1)

array([[11859, 13738, 17797]])